input str15 classnm str25 argnm str40 value str5 newlines
"graphsize" "             " "5" "_n"    
"graphsize " "x           " "9" "_n"    
"graphsize " "y           " "6" "_n(3)"    
"numstyle " "                 " "1" "_n"    
"numstyle " "grid_outer_tol   " "0.23" "_n"    
"numstyle " "legend_rows      " "0" "_n"    
"numstyle " "legend_cols      " "5" "_n"    
"numstyle " "zyx2rows         " "4" "_n"    
"numstyle " "zyx2cols         " "2" "_n(2)"    
"numstyle " "graph_aspect     " "0" "_n(2)"    
"numstyle " "max_wted_symsize " "10" "_n(2)"    
"numstyle " "bar_num_dots    " "100" "_n"    
"numstyle " "dot_num_dots    " "100" "_n"    
"numstyle " "dot_extend_high " "0" "_n"    
"numstyle " "dot_extend_low  " "0" "_n(2)"    
"numstyle " "pie_angle       " "90" "_n(2)"    
"special " "default_slope1  " ".3" "_n"    
"special " "default_knot1    " "4" "_n"    
"special " "default_slope2   " "1" "_n(2)"    
"special " "by_slope1       " ".3" "_n"    
"special " "by_knot1         " "3" "_n"    
"special " "by_slope2        " "1" "_n(2)"    
"special " "combine_slope1  " ".5" "_n"    
"special " "combine_knot1    " "3" "_n"    
"special " "combine_slope2   " "1" "_n(2)"    
"special " "matrix_slope1   " ".3" "_n"    
"special " "matrix_knot1     " "4" "_n"    
"special " "matrix_slope2    " "1" "_n"    
"special " "matrix_yaxis   "  `""ylabels(#3, angle(horizontal) axis(Y))""'  "_n"    
"special " "matrix_xaxis   "  `""xlabels(#3, axis(X))""'  "_n(2)"    
"gsize " "                " "medium" "_n"    
"gsize " "gap             " "tiny" "_n"    
"gsize " "text            " "medsmall" "_n"    
"gsize " "body            " "small" "_n"    
"gsize " "small_body      " "vsmall" "_n"    
"gsize " "heading         " "medlarge" "_n"    
"gsize " "subheading      " "medium" "_n"    
"gsize " "axis_title      " "small" "_n"    
"gsize " "matrix_label    " "medium" "_n"    
"gsize " "label           " "small" "_n"    
"gsize " "small_label     " "vsmall" "_n"    
"gsize " "matrix_marklbl  " "small" "_n"    
"gsize " "key_label       " "small" "_n"    
"gsize " "note            " "vsmall" "_n"    
"gsize " "star            " "small" "_n"    
"gsize " "text_option     " "small" "_n"    
"gsize " "dot_rectangle   " "third_tiny" "_n"    
"gsize " "axis_space      " "half_tiny" "_n"    
"gsize " "axis_title_gap  " "minuscule" "_n"    
"gsize " "tick            " "tiny" "_n"    
"gsize " "minortick       " "third_tiny" "_n"    
"* gsize " "minortick       " ".55" "_n"    
"gsize " "tickgap         " "half_tiny" "_n"    
"gsize " "notickgap       " "tiny" "_n"    
"gsize " "tick_label      " "small" "_n"    
"gsize " "tick_biglabel   " "small" "_n"    
"gsize " "minortick_label " "vsmall" "_n"    
"gsize " "filled_text     " "medsmall" "_n"    
"gsize " "reverse_big     " "large" "_n"    
"gsize " "alternate_gap   " "zero" "_n"    
"gsize " "title_gap       " "small" "_n"    
"gsize " "key_gap         " "small" "_n"    
"gsize " "key_linespace   " "small" "_n"    
"gsize " "star_gap        " "minuscule" "_n"    
"gsize " "legend_colgap   " "medium" "_n"    
"gsize " "label_gap       " "half_tiny" "_n"    
"gsize " "matrix_mlblgap  " "half_tiny" "_n"    
"gsize " "barlabel_gap    " "tiny" "_n(2)"    
"gsize " "legend_row_gap    " "tiny" "_n"    
"gsize " "legend_col_gap    " "large" "_n"    
"gsize " "legend_key_gap    " "vsmall" "_n"    
"gsize " "legend_key_xsize  " "small" "_n"    
"gsize " "legend_key_ysize  " "small" "_n(2)"    
"gsize " "zyx2legend_key_gap    " "tiny" "_n"    
"gsize " "zyx2legend_key_xsize  " "vhuge" "_n"    
"gsize " "zyx2legend_key_ysize  " "medium" "_n"    
"gsize " "zyx2rowgap            " "zero" "_n"    
"gsize " "zyx2colgap            " "large" "_n(2)"    
"gsize " "clegend_width     " "medsmall" "_n"    
"gsize " "clegend_height    " "zero" "_n(2)"    
"gsize " "pie_explode       " "medsmall" "_n"    
"gsize " "pielabel_gap      " "medsmall" "_n(2)"    
"gsize " "plabel            " "vsmall" "_n"    
"gsize " "pboxlabel         " "vsmall" "_n(2)"    
"* gsize " "p#label           " "small" "_n"    
"* gsize " "p#boxlabel        " "small" "_n(2)"    
"gsize " "sts_risktable_space " "tiny" "_n"    
"gsize " "sts_risktable_tgap  " "tiny" "_n"    
"gsize " "sts_risktable_lgap  " "tiny" "_n"    
"gsize " "sts_risk_label      " "medsmall" "_n"    
"gsize " "sts_risk_title      " "medsmall" "_n"    
"gsize " "sts_risk_tick       " "zero" "_n(2)"    
"relsize " "bar_gap            " "0pct" "_n"    
"relsize " "bar_groupgap      " "80pct" "_n"    
"relsize " "bar_supgroupgap  " "200pct" "_n"    
"relsize " "bar_outergap      " "20pct" "_n(2)"    
"relsize " "dot_gap       " "neg100pct" "_n"    
"relsize " "dot_groupgap       " "0pct" "_n"    
"relsize " "dot_supgroupgap   " "75pct" "_n"    
"relsize " "dot_outergap       " "0pct" "_n(2)"    
"relsize " "box_gap           " "50pct" "_n"    
"relsize " "box_groupgap     " "100pct" "_n"    
"relsize " "box_supgroupgap  " "150pct" "_n"    
"relsize " "box_outergap      " "25pct" "_n"    
"relsize " "box_fence         " "75pct" "_n"    
"relsize " "box_fencecap       " "0pct" "_n(3)"    
"symbolsize " "             " "medium" "_n"    
"symbolsize " "symbol       " "medium" "_n"    
"symbolsize " "smallsymbol  " "medsmall" "_n(2)"    
"symbolsize " "star         " "vlarge" "_n"    
"symbolsize " "histogram    " "medium" "_n"    
"symbolsize " "histback     " "vlarge" "_n"    
"symbolsize " "dots         " "vtiny" "_n"    
"symbolsize " "ci           " "medlarge" "_n"    
"symbolsize " "ci2          " "medlarge" "_n"    
"symbolsize " "matrix       " "medsmall" "_n"    
"symbolsize " "refmarker    " "medium" "_n"    
"symbolsize " "sunflower    " "medium" "_n(2)"    
"symbolsize " "backsymbol   " "large" "_n"    
"symbolsize " "backsymspace " "large" "_n"    
"symbolsize " "p            " "medium" "_n"    
"symbolsize " "pback        " "zero" "_n"    
"symbolsize " "parrow       " "medium" "_n"    
"symbolsize " "parrowbarb  " "medsmall" "_n"    
"* symbolsize " "p#         " "large" "_n"    
"* symbolsize " "p#back     " "large" "_n"    
"* symbolsize " "p#box      " "large" "_n"    
"* symbolsize " "p#boxback  " "large" "_n"    
"* symbolsize " "p#dot      " "large" "_n"    
"* symbolsize " "p#dotback  " "large" "_n"    
"* symbolsize " "p#arrow     " "large" "_n"    
"* symbolsize " "p#arrowbarb " "large" "_n(3)"    
"numticks_g " "" "0" "_n"    
"numticks_g " "major " "5" "_n"    
"numticks_g " "horizontal_major " "5" "_n"    
"numticks_g " "vertical_major " "5" "_n"    
"numticks_g " "horizontal_minor " "0" "_n"    
"numticks_g " "vertical_minor " "0" "_n"    
"numticks_g " "horizontal_tmajor " "0" "_n"    
"numticks_g " "vertical_tmajor " "0" "_n"    
"numticks_g " "horizontal_tminor " "0" "_n"    
"numticks_g " "vertical_tminor " "0" "_n(3)"    
"color " "               " "black" "_n"    
"color " "background     " "white" "_n"    
"color " "foreground     " "white" "_n(2)"    
"color " "symbol         " "black" "_n"    
"color " "backsymbol     " "none" "_n(2)"    
"color " "text           " "black" "_n"    
"color " "body           " "black" "_n"    
"color " "small_body     " "black" "_n"    
"color " "heading        " "black" "_n"    
"color " "subheading     " "black" "_n"    
"color " "axis_title     " "black" "_n"    
"color " "matrix_label   " "black" "_n"    
"color " "label          " "black" "_n"    
"color " "key_label      " "black" "_n"    
"color " "tick_label     " "black" "_n"    
"color " "tick_biglabel  " "black" "_n"    
"color " "matrix_marklbl " "black" "_n"    
"color " "sts_risk_label " "black" "_n"    
"color " "sts_risk_title " "black" "_n(2)"    
"color " "box              " "none" "_n"    
"color " "textbox          " "white" "_n"    
"color " "mat_label_box    " "white" "_n(2)"    
"color " "text_option      " "black" "_n"    
"color " "text_option_line " "white" "_n"    
"color " "text_option_fill " "white" "_n(2)"    
"color " "filled_text    " "black" "_n"    
"color " "filled          " "white" "_n"    
"color " "bylabel_outline " "white" "_n(2)"    
"color " "reverse_big      " "none" "_n"    
"color " "reverse_big_line " "black" "_n"    
"color " "reverse_big_text " "white" "_n(2)"    
"color " "grid           " "white" "_n"    
"color " "major_grid     " "white" "_n"    
"color " "minor_grid     " "white" "_n(2)"    
"color " "axisline       " "black" "_n"    
"color " "tick           " "black" "_n"    
"color " "minortick      " "black" "_n(2)"    
"color " "matrix         " "white" "_n"    
"color " "matrixmarkline " "black" "_n"    
"color " "histback       " "white" "_n"    
"color " "plotregion         " "white" "_n"    
"color " "plotregion_line    " "white" "_n"    
"color " "matrix_plotregion  " "white" "_n"    
"color " "matplotregion_line " "black" "_n"    
"color " "legend             " "white" "_n"    
"color " "legend_line        " "white" "_n"    
"color " "clegend            " "none" "_n"    
"color " "clegend_outer      " "none" "_n"    
"color " "clegend_inner      " "none" "_n"    
"color " "clegend_line       " "none" "_n(2)"    
"color " "pboxlabelfill " "white" "_n"    
"color " "plabelfill " "white" "_n(2)"    
"color " "pmarkback " "white" "_n"    
"color " "pmarkbkfill " "white" "_n(2)"    
"* color " "p#              " "yellow" "_n"    
"* color " "p#line          " "yellow" "_n"    
"* color " "p#lineplot      " "yellow" "_n"    
"* color " "p#bar           " "yellow" "_n"    
"* color " "p#barline       " "yellow" "_n"    
"* color " "p#box           " "yellow" "_n"    
"* color " "p#boxline       " "yellow" "_n"    
"* color " "p#pie           " "yellow" "_n"    
"* color " "p#area          " "yellow" "_n"    
"* color " "p#arealine      " "yellow" "_n"    
"* color " "p#other         " "yellow" "_n"    
"* color " "p#otherline     " "yellow" "_n"    
"* color " "p#mark          " "yellow" "_n"    
"* color " "p#markfill      " "none" "_n"    
"* color " "p#markline      " "yellow" "_n"    
"* color " "p#markback      " "yellow" "_n"    
"* color " "p#markbkfill    " "yellow" "_n"    
"* color " "p#boxmarkfill   " "yellow" "_n"    
"* color " "p#boxmarkbkfill " "yellow" "_n"    
"* color " "p#boxmarkline   " "yellow" "_n"    
"* color " "p#dotmarkfill   " "yellow" "_n"    
"* color " "p#dotmarkbkfill " "yellow" "_n"    
"* color " "p#dotmarkline   " "yellow" "_n"    
"* color " "p#arrow         " "yellow" "_n"    
"* color " "p#arrowline     " "yellow" "_n"    
"* color " "p#arrowfill     " "yellow" "_n"    
"* color " "p#label         " "white" "_n"    
"* color " "p#boxlabel      " "yellow" "_n"    
"* color " "p#boxlabelfill  " "yellow" "_n"    
"* color " "p#labelfill     " "yellow" "_n"    
"* color " "p#shade         " "yellow" "_n(2)"    
"* color " "p1markfill     " "light_xyz" "_n"    
"* color " "p2markfill     " "light_xyz" "_n"    
"* color " "p3markfill     " "light_xyz" "_n"    
"* color " "p4markfill     " "light_xyz" "_n"    
"* color " "p5markfill     " "light_xyz" "_n"    
"* color " "p6markfill     " "light_xyz" "_n"    
"* color " "p1markfill     " "none" "_n"    
"* color " "p2markfill     " "none" "_n"    
"* color " "p3markfill     " "none" "_n"    
"* color " "p4markfill     " "none" "_n"    
"* color " "p5markfill     " "none" "_n"    
"* color " "p6markfill     " "none" "_n"    
"* color " "p1mark         " "yellow" "_n"    
"* color " "p2mark         " "red" "_n"    
"* color " "p3mark         " "blue" "_n(3)"    
"symbol " "" "circle" "_n"    
"symbol " "sunflower " "circle_hollow" "_n(2)"    
"symbol " "none " "none" "_n"    
"symbol " "histogram " "circle" "_n"    
"symbol " "histback " "none" "_n"    
"symbol " "dots " "circle" "_n"    
"symbol " "ci " "circle" "_n"    
"symbol " "ci2 " "circle" "_n"    
"symbol " "ilabel " "none" "_n"    
"symbol " "matrix " "circle" "_n"    
"symbol " "refmarker " "circle" "_n(2)"    
"symbol " "p " "circle" "_n"    
"symbol " "pback " "none" "_n"    
"symbol " "pbarback " "none" "_n"    
"symbol " "pdotback " "none" "_n(2)"    
"* symbol " "p#         " "circle" "_n"    
"* symbol " "p#back     " "none" "_n"    
"* symbol " "p#box      " "circle" "_n"    
"* symbol " "p#boxback  " "circle" "_n"    
"* symbol " "p#dot      " "circle" "_n"    
"* symbol " "p#dotback  " "circle" "_n"    
"* symbol " "p#arrow    " "circle" "_n(2)"    
"* symbol " "p1     " "circle" "_n"    
"* symbol " "p2     " "diamond" "_n"    
"* symbol " "p3     " "square" "_n"    
"* symbol " "p4     " "triangle" "_n"    
"* symbol " "p5     " "x" "_n"    
"* symbol " "p6     " "plus" "_n"    
"* symbol " "p7     " "circle_hollow" "_n"    
"* symbol " "p8     " "diamond_hollow" "_n"    
"* symbol " "p9     " "square_hollow" "_n"    
"* symbol " "p10    " "triangle_hollow" "_n"    
"* symbol " "p11    " "smcircle" "_n"    
"* symbol " "p12    " "smdiamond" "_n"    
"* symbol " "p13    " "smsquare" "_n"    
"* symbol " "p14    " "smtriangle" "_n"    
"* symbol " "p15    " "smx" "_n(3)"    
"linepattern " "" "solid" "_n"    
"linepattern " "foreground " "blank" "_n"    
"linepattern " "background " "solid" "_n"    
"linepattern " "ci " "solid" "_n"    
"linepattern " "ci_area " "solid" "_n"    
"linepattern " "histogram " "solid" "_n"    
"linepattern " "dendrogram " "solid" "_n"    
"linepattern " "grid " "blank" "_n"    
"linepattern " "major_grid " "blank" "_n"    
"linepattern " "minor_grid " "blank" "_n"    
"linepattern " "axisline " "solid" "_n"    
"linepattern " "tick " "solid" "_n"    
"linepattern " "minortick " "solid" "_n"    
"linepattern " "xyline " "solid" "_n"    
"linepattern " "refline " "solid" "_n"    
"linepattern " "refmarker " "solid" "_n"    
"linepattern " "matrixmark " "solid" "_n"    
"linepattern " "dots " "solid" "_n"    
"linepattern " "dot " "solid" "_n"    
"linepattern " "dot_area " "solid" "_n"    
"linepattern " "dotmark " "solid" "_n"    
"linepattern " "pie " "solid" "_n"    
"linepattern " "legend " "solid" "_n"    
"linepattern " "clegend " "solid" "_n"    
"linepattern " "plotregion " "solid" "_n"    
"linepattern " "sunflower " "solid" "_n"    
"linepattern " "matrix_plotregion " "solid" "_n"    
"linepattern " "text_option " "blank" "_n"    
"linepattern " "zyx2 " "solid" "_n(2)"    
"linepattern " "p " "solid" "_n"    
"linepattern " "pmark " "solid" "_n(2)"    
"* linepattern " "p#         " "dash" "_n"    
"* linepattern " "p#line     " "dash" "_n"    
"* linepattern " "p#lineplot " "dash" "_n"    
"* linepattern " "p#bar      " "dash" "_n"    
"* linepattern " "p#box      " "dash" "_n"    
"* linepattern " "p#pie      " "dash" "_n"    
"* linepattern " "p#area     " "dash" "_n"    
"* linepattern " "p#other    " "dash" "_n"    
"* linepattern " "p#mark     " "solid" "_n"    
"* linepattern " "p#boxmark  " "solid" "_n"    
"* linepattern " "p#dotmark  " "solid" "_n"    
"* linepattern " "p#arrow    " "solid" "_n"    
"* linepattern " "p#arrowline " "solid" "_n(2)"    
"* linepattern " "p1line  " "solid" "_n"    
"* linepattern " "p2line  " "dash" "_n"    
"* linepattern " "p3line  " "longdash" "_n"    
"* linepattern " "p4line  " "dot" "_n"    
"* linepattern " "p5line  " "longdash_dot" "_n"    
"* linepattern " "p6line  " "dash_dot" "_n"    
"* linepattern " "p8line  " "shortdash" "_n"    
"* linepattern " "p9line  " "shortdash_dot" "_n(3)"    
"margin " "" "zero" "_n"    
"margin " "graph " "medium" "_n"    
"margin " "twoway " "medsmall" "_n"    
"margin " "bygraph " "zero" "_n"    
"margin " "combinegraph " "medsmall" "_n"    
"margin " "combine_region " "zero" "_n"    
"margin " "matrixgraph " "zero" "_n"    
"margin " "piegraph " "small" "_n"    
"margin " "piegraph_region " "medsmall" "_n"    
"margin " "matrix_plotreg " "small" "_n"    
"margin " "matrix_label " "zero" "_n"    
"margin " "mat_label_box " "zero" "_n"    
"margin " "by_indiv " "small" "_n"    
"margin " "text " "vsmall" "_n"    
"margin " "textbox " "zero" "_n"    
"margin " "body " "vsmall" "_n"    
"margin " "small_body " "vsmall" "_n"    
"margin " "heading " "vsmall" "_n"    
"* margin " "heading " `"".6 .6 .6 .6""' "_n"    
"margin " "subheading " "vsmall" "_n"    
"margin " "axis_title " "zero" "_n"    
"margin " "label " "zero" "_n"    
"margin " "key_label " "zero" "_n"    
"margin " "text_option " "zero" "_n"    
"margin " "plotregion " "medsmall" "_n"    
"margin " "star " "tiny" "_n"    
"margin " "bargraph " "bargraph" "_n"    
"margin " "boxgraph " "bargraph" "_n"    
"margin " "dotgraph " "bargraph" "_n"    
"margin " "hbargraph " "bargraph" "_n"    
"margin " "hboxgraph " "bargraph" "_n"    
"margin " "hdotgraph " "bargraph" "_n"    
"margin " "legend " "small" "_n"    
"margin " "legend_key_region " "tiny" "_n"    
"margin " "legend_boxmargin " "small" "_n"    
"margin " "clegend " "medium" "_n"    
"margin " "cleg_title " "medsmall" "_n"    
"margin " "clegend_boxmargin " "small" "_n"    
"margin " "key_label " "zero" "_n"    
"margin " "filled_textbox " "small" "_n"    
"margin " "filled_box " "zero" "_n"    
"margin " "editor " "zero" "_n(2)"    
"margin " "plabel " "zero" "_n"    
"margin " "plabelbox " "zero" "_n"    
"margin " "pboxlabel " "zero" "_n"    
"margin " "pboxlabelbox " "zero" "_n(2)"    
"* margin " "p#label           " "zero" "_n"    
"* margin " "p#labelbox        " "zero" "_n"    
"* margin " "p#boxlabel        " "zero" "_n"    
"* margin " "p#boxlabelbox     " "zero" "_n"    
"" "" "" "_n(4)"    
"linestyle " "" "foreground" "_n"    
"linestyle " "background " "background" "_n"    
"linestyle " "foreground " "foreground" "_n(2)"    
"linestyle " "symbol " "symbol" "_n"    
"linestyle " "boxline " "foreground" "_n"    
"linestyle " "textbox " "none" "_n"    
"linestyle " "axis " "axisline" "_n"    
"linestyle " "axis_withgrid " "foreground" "_n"    
"linestyle " "zero_line " "foreground" "_n"    
"linestyle " "tick "  "tick" "_n"    
"linestyle " "minortick "  "minortick" "_n"    
"linestyle " "star "  "p1" "_n"    
"linestyle " "ci " "ci" "_n"    
"linestyle " "ci_area " "ci_area" "_n"    
"linestyle " "ci2 " "ci2" "_n"    
"linestyle " "ci2_area " "ci2_area" "_n"    
"linestyle " "histogram "  "histogram" "_n"    
"linestyle " "histback " "histogram" "_n"    
"linestyle " "dendrogram " "dendrogram" "_n"    
"linestyle " "grid " "none" "_n"    
"linestyle " "major_grid " "none" "_n"    
"linestyle " "minor_grid " "none" "_n"    
"linestyle " "xyline " "xyline" "_n"    
"linestyle " "refline " "refline" "_n"    
"linestyle " "refmarker " "refmarker" "_n"    
"linestyle " "matrixmark " "matrixmark" "_n"    
"linestyle " "matrix " "p1solid" "_n"    
"linestyle " "dotchart " "dotchart" "_n"    
"linestyle " "dotchart_area " "dotchart_area" "_n"    
"linestyle " "dotmark " "dotmark" "_n"    
"linestyle " "box_whiskers " "ci" "_n"    
"linestyle " "box_median " "refline" "_n"    
"linestyle " "pie_lines " "pie" "_n"    
"linestyle " "legend " "none" "_n"    
"linestyle " "clegend " "clegend" "_n"    
"linestyle " "clegend_outer " "none" "_n"    
"linestyle " "clegend_inner " "none" "_n"    
"linestyle " "clegend_preg " "foreground" "_n"    
"linestyle " "mat_label_box " "foreground" "_n"    
"linestyle " "reverse_big " "reverse_big" "_n"    
"linestyle " "plotregion " "plotregion" "_n"    
"linestyle " "matrix_plotregion " "matrix_plotregion" "_n"    
"linestyle " "dots " "dot" "_n"    
"linestyle " "editor " "editor" "_n"    
"linestyle " "sunflower " "sunflower" "_n"    
"linestyle " "sunflowerlb " "sunflowerlb" "_n"    
"linestyle " "sunflowerlf " "sunflowerlf" "_n"    
"linestyle " "sunflowerdb " "sunflowerdb" "_n"    
"linestyle " "sunflowerdf " "sunflowerdf" "_n"    
"linestyle " "text_option " "text_option" "_n"    
"linestyle " "sts_risktable " "none" "_n"    
"linestyle " "zyx2 " "zyx2" "_n(2)"    
"linestyle " "pmarkback " "background" "_n"    
"linestyle " "pboxmarkback " "background" "_n(2)"    
"linestyle " "plabel " "foreground" "_n"    
"linestyle " "pboxlabel " "foreground" "_n(2)"    
"* linestyle " "p#connect     " "foreground" "_n"    
"* linestyle " "p#markback    " "foreground" "_n"    
"* linestyle " "p#boxmarkback " "foreground" "_n"    
"* linestyle " "p#dotmarkback " "foreground" "_n"    
"* linestyle " "p#label       " "xyz" "_n"    
"* linestyle " "p#boxlabel    " "xyz" "_n(3)"    
"linewidth " "thin " "thin" "_n"    
"linewidth " "medium " "medium" "_n"    
"linewidth " "p " "vthin" "_n"    
"linewidth " "foreground " "none" "_n"    
"linewidth " "background " "none" "_n"    
"linewidth " "grid " "none" "_n"    
"linewidth " "major_grid " "none" "_n"    
"linewidth " "minor_grid " "none" "_n"    
"linewidth " "axisline " "thin" "_n"    
"linewidth " "tick " "vthin" "_n"    
"linewidth " "minortick " "vvthin" "_n"    
"linewidth " "ci " "medium" "_n"    
"linewidth " "ci_area " "medthin" "_n"    
"linewidth " "ci2 " "medium" "_n"    
"linewidth " "ci2_area " "medthin" "_n"    
"linewidth " "histogram " "vthin" "_n"    
"linewidth " "dendrogram " "medium" "_n"    
"linewidth " "xyline " "medthin" "_n"    
"linewidth " "refline " "medium" "_n"    
"linewidth " "refmarker " "medthin" "_n"    
"linewidth " "matrixmark " "vvthin" "_n"    
"linewidth " "dots " "vthin" "_n"    
"linewidth " "dot_line " "medthick" "_n"    
"linewidth " "dot_area " "medthin" "_n"    
"linewidth " "dotmark " "vthin" "_n"    
"linewidth " "plotregion " "vthin" "_n"    
"linewidth " "legend " "none" "_n"    
"linewidth " "clegend " "none" "_n"    
"linewidth " "pie " "vthin" "_n"    
"linewidth " "reverse_big " "thin" "_n"    
"linewidth " "sunflower " "thin" "_n"    
"linewidth " "matrix_plotregion " "thin" "_n"    
"linewidth " "text_option " "none" "_n"    
"linewidth " "zyx2 " "medium" "_n(2)"    
"linewidth " "pbar " "vthin" "_n(2)"    
"* linewidth " "p#         " "medium" "_n"    
"* linewidth " "p#solid    " "thin" "_n"    
"* linewidth " "p#lineplot " "thin" "_n"    
"* linewidth " "p#bar      " "thin" "_n"    
"* linewidth " "p#box      " "thin" "_n"    
"* linewidth " "p#area     " "thin" "_n"    
"* linewidth " "p#other    " "thin" "_n"    
"* linewidth " "p#mark     " "thin" "_n"    
"* linewidth " "p#boxmark  " "thin" "_n"    
"* linewidth " "p#dotmark  " "thin" "_n"    
"* linewidth " "p#arrow    " "thin" "_n"    
"* linewidth " "p#arrowline " "thin" "_n(3)"    
"connectstyle " "" "direct" "_n"    
"connectstyle " "p " "direct" "_n"    
"* connectstyle " "p#   " "direct" "_n(3)"    
"textboxstyle " "" "body" "_n"    
"textboxstyle " "title " "heading" "_n"    
"textboxstyle " "subtitle " "subheading" "_n"    
"textboxstyle " "caption " "body" "_n"    
"textboxstyle " "note " "body" "_n(2)"    
"textboxstyle " "leg_title " "heading" "_n"    
"textboxstyle " "leg_subtitle " "subheading" "_n"    
"textboxstyle " "leg_caption " "small_body" "_n"    
"textboxstyle " "leg_note " "small_body" "_n"    
"textboxstyle " "cleg_title " "clegend" "_n"    
"textboxstyle " "cleg_subtitle " "subheading" "_n"    
"textboxstyle " "cleg_caption " "body" "_n"    
"textboxstyle " "cleg_note " "small_body" "_n(2)"    
"textboxstyle " "t1title " "subheading" "_n"    
"textboxstyle " "t2title " "body" "_n"    
"textboxstyle " "b1title " "subheading" "_n"    
"textboxstyle " "b2title " "body" "_n"    
"textboxstyle " "r1title " "subheading" "_n"    
"textboxstyle " "r2title " "body" "_n"    
"textboxstyle " "l1title " "subheading" "_n"    
"textboxstyle " "l2title " "body" "_n(2)"    
"textboxstyle " "heading " "heading" "_n"    
"textboxstyle " "subheading " "subheading" "_n"    
"textboxstyle " "body " "body" "_n(2)"    
"textboxstyle " "text_option " "text_option" "_n"    
"textboxstyle " "legend_key " "legend_key" "_n"    
"textboxstyle " "barlabel " "small_label" "_n"    
"textboxstyle " "axis_title " "axis_title" "_n"    
"textboxstyle " "matrix_label " "matrix_label" "_n"    
"textboxstyle " "pielabel " "small_label" "_n"    
"textboxstyle " "tick " "tick_label" "_n"    
"textboxstyle " "minortick " "minortick_label" "_n"    
"textboxstyle " "bigtick " "tick_biglabel" "_n"    
"textboxstyle " "sts_risktable " "sts_risktable" "_n(2)"    
"textboxstyle " "label " "label" "_n"    
"textboxstyle " "ilabel " "small_label" "_n"    
"textboxstyle " "key_label " "key_label" "_n"    
"textboxstyle " "small_label " "small_label" "_n"    
"textboxstyle " "matrix_marklbl " "matrix_marklbl" "_n(2)"    
"textboxstyle " "star " "star_label" "_n"    
"textboxstyle " "bytitle " "bytitle" "_n(2)"    
"textboxstyle " "editor " "editor" "_n(2)"    
"areastyle " "" "background" "_n"    
"areastyle " "foreground " "foreground" "_n"    
"areastyle " "background " "background" "_n(2)"    
"areastyle " "plotregion " "plotregion" "_n"    
"areastyle " "inner_plotregion " "none" "_n"    
"areastyle " "twoway_plotregion " "plotregion" "_n"    
"areastyle " "twoway_iplotregion " "none" "_n"    
"areastyle " "bar_plotregion " "plotregion" "_n"    
"areastyle " "bar_iplotregion " "none" "_n"    
"areastyle " "hbar_plotregion " "plotregion" "_n"    
"areastyle " "hbar_iplotregion " "none" "_n"    
"areastyle " "dot_plotregion " "plotregion" "_n"    
"areastyle " "dot_iplotregion " "none" "_n"    
"areastyle " "box_plotregion " "plotregion" "_n"    
"areastyle " "box_iplotregion " "none" "_n"    
"areastyle " "hbox_plotregion " "plotregion" "_n"    
"areastyle " "hbox_iplotregion " "none" "_n"    
"areastyle " "combine_plotregion " "none" "_n"    
"areastyle " "combine_iplotregion " "none" "_n"    
"areastyle " "bygraph_plotregion " "none" "_n"    
"areastyle " "bygraph_iplotregion " "none" "_n"    
"areastyle " "matrixgraph_plotregion " "none" "_n"    
"areastyle " "matrixgraph_iplotregion " "none" "_n(2)"    
"areastyle " "matrix_plotregion " "matrix_plotregion" "_n"    
"areastyle " "matrix_iplotregion " "none" "_n(2)"    
"areastyle " "legend " "legend" "_n"    
"areastyle " "legend_key_region " "none" "_n"    
"areastyle " "legend_inkey_region " "none" "_n"    
"areastyle " "inner_legend " "none" "_n"    
"areastyle " "clegend " "clegend_preg" "_n"    
"areastyle " "clegend_preg " "none" "_n"    
"areastyle " "clegend_inpreg " "none" "_n"    
"areastyle " "clegend_outer " "clegend_outer" "_n"    
"areastyle " "clegend_inner " "clegend_inner" "_n(2)"    
"areastyle " "graph " "background" "_n"    
"areastyle " "inner_graph " "none" "_n"    
"areastyle " "bygraph " "background" "_n"    
"areastyle " "inner_bygraph " "none" "_n"    
"areastyle " "piegraph " "background" "_n"    
"areastyle " "piegraph_region " "plotregion" "_n"    
"areastyle " "inner_pieregion " "none" "_n"    
"areastyle " "inner_piegraph " "none" "_n"    
"areastyle " "combinegraph " "background" "_n"    
"areastyle " "combinegraph_inner " "none" "_n(2)"    
"areastyle " "matrix_label " "background" "_n"    
"areastyle " "matrix_ilabel " "none" "_n(2)"    
"areastyle " "ci " "ci" "_n"    
"areastyle " "ci2 " "ci2" "_n"    
"areastyle " "histogram " "histogram" "_n"    
"areastyle " "dendrogram " "dendrogram" "_n"    
"areastyle " "dotchart " "dotchart" "_n(2)"    
"areastyle " "sunflower " "sunflower" "_n"    
"areastyle " "sunflowerlb " "sunflowerlb" "_n"    
"areastyle " "sunflowerdb " "sunflowerdb" "_n(2)"    
"horizontal " "" "center" "_n"    
"horizontal " "heading " "center" "_n"    
"horizontal " "subheading " "center" "_n"    
"horizontal " "label " "center" "_n"    
"horizontal " "key_label " "left" "_n"    
"horizontal " "body " "center" "_n"    
"horizontal " "small_body " "center" "_n"    
"horizontal " "axis_title " "center" "_n"    
"horizontal " "matrix_label " "center" "_n"    
"horizontal " "filled " "center" "_n"    
"horizontal " "text_option " "center" "_n"    
"horizontal " "editor " "left" "_n"    
"horizontal " "sts_risk_label " "default" "_n"    
"horizontal " "sts_risk_title " "right" "_n(3)"    
"vertical " "" "bottom" "_n"    
"vertical_text " "" "bottom" "_n"    
"vertical_text " "heading " "bottom" "_n"    
"vertical_text " "subheading " "bottom" "_n"    
"vertical_text " "label " "middle" "_n"    
"vertical_text " "key_label " "middle" "_n"    
"vertical_text " "body " "bottom" "_n"    
"vertical_text " "small_body " "bottom" "_n"    
"vertical_text " "axis_title " "bottom" "_n"    
"vertical_text " "matrix_label " "middle" "_n"    
"vertical_text " "legend " "bottom" "_n"    
"vertical_text " "text_option " "middle" "_n"    
"vertical_text " "filled " "middle" "_n(2)"    
"tb_orientstyle " "" "horizontal " "_n(2)"    
"axisstyle " "" "horizontal_default" "_n"    
"axisstyle " "horizontal_default " "horizontal_default" "_n"    
"axisstyle " "vertical_default   " "vertical_default" "_n"    
"axisstyle " "horizontal_nogrid  " "horizontal_nogrid" "_n"    
"axisstyle " "vertical_nogrid    " "vertical_nogrid" "_n"    
"axisstyle " "bar_super          " "horizontal_nogrid" "_n"    
"axisstyle " "dot_super          " "horizontal_nogrid" "_n"    
"axisstyle " "bar_group          " "horizontal_notick" "_n"    
"axisstyle " "dot_group          " "horizontal_notick" "_n"    
"axisstyle " "bar_var            " "horizontal_notick" "_n"    
"axisstyle " "dot_var            " "horizontal_notick" "_n"    
"axisstyle " "bar_scale_horiz    " "horizontal_nogrid" "_n"    
"axisstyle " "bar_scale_vert     " "vertical_nogrid" "_n"    
"axisstyle " "dot_scale_horiz    " "horizontal_nogrid" "_n"    
"axisstyle " "dot_scale_vert     " "vertical_nogrid" "_n"    
"axisstyle " "box_scale_horiz    " "horizontal_nogrid" "_n"    
"axisstyle " "box_scale_vert     " "vertical_nogrid" "_n"    
"axisstyle " "matrix_horiz       " "horizontal_nogrid" "_n"    
"axisstyle " "matrix_vert        " "vertical_nogrid" "_n"    
"axisstyle " "sts_risktable      " "sts_risktable" "_n"    
"axisstyle " "clegend            " "clegend" "_n(3)"    
"gridstyle " "" "default" "_n"    
"gridstyle " "major " "major" "_n"    
"gridstyle " "minor " "major" "_n(3)"    
"gridlinestyle " "" "default" "_n"    
"gridlinestyle " "default " "default" "_n(3)"    
"tickstyle " "" "default" "_n"    
"tickstyle " "default " "default" "_n"    
"tickstyle " "major " "major" "_n"    
"tickstyle " "minor " "minor" "_n"    
"tickstyle " "major_nolabel " "major_nolabel" "_n"    
"tickstyle " "minor_nolabel " "minor_nolabel" "_n"    
"tickstyle " "major_notick " "major_notick" "_n"    
"tickstyle " "minor_notick " "minor_notick" "_n"    
"tickstyle " "major_notickbig " "major_notickbig" "_n"    
"tickstyle " "minor_notickbig " "minor_notickbig" "_n"    
"tickstyle " "sts_risktable " "sts_risktable" "_n(3)"    
"ticksetstyle " "" "major_horiz_default" "_n"    
"ticksetstyle " "major_horiz_default " "major_horiz_default" "_n"    
"ticksetstyle " "major_vert_default " "major_vert_default" "_n"    
"ticksetstyle " "minor_horiz_default " "minor_horiz_default" "_n"    
"ticksetstyle " "minor_vert_default " "minor_vert_default" "_n"    
"ticksetstyle " "major_horiz_withgrid " "major_horiz_default" "_n"    
"ticksetstyle " "major_vert_withgrid " "major_vert_default" "_n"    
"ticksetstyle " "major_horiz_nolabel " "major_horiz_nolabel" "_n"    
"ticksetstyle " "major_vert_nolabel " "major_vert_nolabel" "_n"    
"ticksetstyle " "minor_horiz_nolabel " "minor_horiz_nolabel" "_n"    
"ticksetstyle " "minor_vert_nolabel " "minor_vert_nolabel" "_n"    
"ticksetstyle " "major_horiz_notick " "major_horiz_notick" "_n"    
"ticksetstyle " "major_vert_notick " "major_vert_notick" "_n"    
"ticksetstyle " "minor_horiz_notick " "minor_horiz_notick" "_n"    
"ticksetstyle " "minor_vert_notick " "minor_vert_notick" "_n"    
"ticksetstyle " "major_horiz_notickbig " "major_horiz_notickbig" "_n"    
"ticksetstyle " "major_vert_notickbig " "major_vert_notickbig" "_n"    
"ticksetstyle " "sts_risktable " "sts_risktable" "_n"    
"ticksetstyle " "major_clegend " "major_clegend" "_n(2)"    
"tickposition " "axis_tick " "outside" "_n(2)"    
"barlabelpos " "bar " "outside" "_n(2)"    
"compass2dir " "" "east" "_n"    
"compass2dir " "p " "east" "_n"    
"compass2dir " "key_label " "west" "_n"    
"compass2dir " "legend_fillpos " "center" "_n"    
"compass2dir " "legend_key " "default" "_n"    
"compass2dir " "text_option " "center" "_n"    
"compass2dir " "graph_aspect " "center" "_n"    
"compass2dir " "editor " "east" "_n"    
"* compass2dir " "" "p#" "_n(3)"    
"compass3dir " "" "east" "_n"    
"compass3dir " "p " "east" "_n"    
"* compass3dir " "" "p#" "_n(3)"    
"clockdir " "" "12" "_n"    
"clockdir " "title_position " "12" "_n"    
"clockdir " "subtitle_position " "12" "_n"    
"clockdir " "caption_position " "5" "_n"    
"clockdir " "note_position " "7" "_n"    
"clockdir " "legend_position " "12" "_n"    
"clockdir " "zyx2legend_position " "3" "_n"    
"clockdir " "by_legend_position " "12" "_n"    
"clockdir " "ilabel " "3" "_n"    
"clockdir " "matrix_marklbl " "12" "_n(2)"    
"clockdir " "p " "0" "_n"    
"* clockdir " "p#                   " "3" "_n"    
"* clockdir " "p#box                " "3" "_n(2)"    
"clockdir " "legend_title_position " "12" "_n"    
"clockdir " "legend_subtitle_position " "12" "_n"    
"clockdir " "legend_caption_position " "5" "_n"    
"clockdir " "legend_note_position " "7" "_n"    
"clockdir " "clegend_title_position " "12" "_n(2)"    
"relative_posn " "zyx2legend_pos " "right" "_n"    
"relative_posn " "clegend_pos " "right" "_n"    
"relative_posn " "clegend_axispos " "right" "_n(2)"    
"gridringstyle " "spacers_ring " "11" "_n"    
"gridringstyle " "title_ring " "7" "_n"    
"gridringstyle " "subtitle_ring " "6" "_n"    
"gridringstyle " "caption_ring " "4" "_n"    
"gridringstyle " "note_ring " "4" "_n"    
"gridringstyle " "legend_ring " "3" "_n"    
"gridringstyle " "zyx2legend_ring " "4" "_n"    
"gridringstyle " "clegend_ring " "3" "_n"    
"gridringstyle " "by_legend_ring " "3" "_n(2)"    
"gridringstyle " "legend_title_ring " "7" "_n"    
"gridringstyle " "legend_subtitle_ring " "6" "_n"    
"gridringstyle " "legend_caption_ring " "3" "_n"    
"gridringstyle " "legend_note_ring " "3" "_n"    
"gridringstyle " "clegend_title_ring " "7" "_n(3)"    
"anglestyle " "" "horizontal " "_n"    
"anglestyle " "horizontal_tick " "horizontal " "_n"    
"anglestyle " "vertical_tick " "horizontal " "_n"    
"anglestyle " "clegend " "horizontal " "_n"    
"anglestyle " "p " "stdarrow" "_n"    
"anglestyle " "parrow " "stdarrow" "_n"    
"anglestyle " "parrowbarb " "zero" "_n"    
"* anglestyle " "" "p#mark" "_n"    
"* anglestyle " "" "p#backmark" "_n"    
"* anglestyle " "" "p#arrow" "_n"    
"* anglestyle " "" "p#arrowbarb" "_n(3)"    
`"plotregionstyle "' `" "' `"default"' `"_n"'    
`"plotregionstyle "' `" graph "' `"graph"' `"_n"'    
`"plotregionstyle "' `" twoway "' `"twoway"' `"_n"'    
`"plotregionstyle "' `" bygraph "' `"bygraph"' `"_n"'    
`"plotregionstyle "' `" combinegraph "' `"matrixgraph"' `"_n"'   
`"plotregionstyle "' `" combineregion "' `"combineregion"' `"_n"'    
`"plotregionstyle "' `" matrixgraph "' `"matrixgraph"' `"_n"'
`"plotregionstyle "' `" bargraph "' `"bargraph"' `"_n"'    
`"plotregionstyle "' `" hbargraph "' `"hbargraph"' `"_n"'    
`"plotregionstyle "' `" boxgraph "' `"boxgraph"' `"_n"'    
`"plotregionstyle "' `" hboxgraph "' `"hboxgraph"' `"_n"'    
`"plotregionstyle "' `" piegraph "' `"piegraph"' `"_n"'    
`"plotregionstyle "' `" matrix "' `"matrix"' `"_n"'
`"plotregionstyle "' `" matrix_label "' `"matrix_label"' `"_n"'
`"plotregionstyle "' `" legend_key_region "' `"legend_key_region"' `"_n"'
`"plotregionstyle "' `" clegend "' `"clegend"' `"_n(3)"'
"graphstyle " "" "default" "_n"    
"graphstyle " "default " "default" "_n"    
"graphstyle " "graph " "default" "_n"    
"graphstyle " "matrixgraph " "matrixgraph" "_n(3)"    
"bygraphstyle " "" "default" "_n"    
"bygraphstyle " "default " "default" "_n"    
"bygraphstyle " "bygraph " "default" "_n"    
"bygraphstyle " "combine " "combine" "_n(2)"    
"piegraphstyle " "" "default" "_n"    
"piegraphstyle " "piegraph " "default" "_n(3)"    
"legendstyle " "" "default" "_n"    
"legendstyle " "default " "default" "_n"    
"legendstyle " "zyx2 " "zyx2" "_n(2)"    
"clegendstyle " "" "default" "_n"    
"clegendstyle " "default " "default" "_n(3)"    
"labelstyle " "" "default" "_n"    
"labelstyle " "ilabel " "ilabel" "_n"    
"labelstyle " "matrix " "matrix" "_n"    
"labelstyle " "editor " "editor" "_n"    
"labelstyle " "sunflower " "default" "_n(2)"    
"yesno " "textbox " "no" "_n"    
"yesno " "text_option " "no" "_n(2)"    
"yesno " "connect_missings " "yes" "_n"    
"yesno " "cmissings " "yes" "_n"    
"yesno " "pcmissings " "yes" "_n"    
"* yesno " "p#cmissings       " "no" "_n(2)"    
"yesno " "extend_axes_low " "yes" "_n"    
"yesno " "extend_axes_high " "yes" "_n"    
"yesno " "extend_axes_full_low " "yes" "_n"    
"yesno " "extend_axes_full_high " "yes" "_n(2)"    
"yesno " "draw_major_grid " "no" "_n"    
"yesno " "draw_minor_grid " "no" "_n"    
"yesno " "draw_majornl_grid " "no" "_n"    
"yesno " "draw_minornl_grid " "no" "_n"    
"yesno " "draw_major_hgrid " "no" "_n"    
"yesno " "draw_minor_hgrid " "no" "_n"    
"yesno " "draw_majornl_hgrid " "no" "_n"    
"yesno " "draw_minornl_hgrid " "no" "_n"    
"yesno " "draw_major_vgrid " "no" "_n"    
"yesno " "draw_minor_vgrid " "no" "_n"    
"yesno " "draw_majornl_vgrid " "no" "_n"    
"yesno " "draw_minornl_vgrid " "no" "_n"    
"yesno " "draw_major_nl_vgrid " "no" "_n"    
"yesno " "draw_minor_nl_vgrid " "no" "_n"    
"yesno " "draw_majornl_nl_vgrid " "no" "_n"    
"yesno " "draw_minornl_nl_vgrid " "no" "_n"    
"yesno " "draw_major_nl_hgrid " "no" "_n"    
"yesno " "draw_minor_nl_hgrid " "no" "_n"    
"yesno " "draw_majornl_nl_hgrid " "no" "_n"    
"yesno " "draw_minornl_nl_hgrid " "no" "_n"    
"yesno " "draw_major_nt_vgrid " "no" "_n"    
"yesno " "draw_minor_nt_vgrid " "no" "_n"    
"yesno " "draw_majornl_nt_vgrid " "no" "_n"    
"yesno " "draw_minornl_nt_vgrid " "no" "_n"    
"yesno " "draw_major_nt_hgrid " "no" "_n"    
"yesno " "draw_minor_nt_hgrid " "no" "_n"    
"yesno " "draw_majornl_nt_hgrid " "no" "_n"    
"yesno " "draw_minornl_nt_hgrid " "no" "_n"    
"yesno " "draw_major_nlt_vgrid " "no" "_n"    
"yesno " "draw_minor_nlt_vgrid " "no" "_n"    
"yesno " "draw_majornl_nlt_vgrid " "no" "_n"    
"yesno " "draw_minornl_nlt_vgrid " "no" "_n"    
"yesno " "draw_major_nlt_hgrid " "no" "_n"    
"yesno " "draw_minor_nlt_hgrid " "no" "_n"    
"yesno " "draw_majornl_nlt_hgrid " "no" "_n"    
"yesno " "draw_minornl_nlt_hgrid " "no" "_n"    
"yesno " "extend_grid_low " "yes" "_n"    
"yesno " "extend_grid_high " "yes" "_n"    
"yesno " "extend_minorgrid_low " "yes" "_n"    
"yesno " "extend_minorgrid_high " "yes" "_n"    
"yesno " "extend_majorgrid_low " "yes" "_n"    
"yesno " "extend_majorgrid_high " "yes" "_n"    
"yesno " "grid_draw_min " "no" "_n"    
"yesno " "grid_draw_max " "no" "_n"    
"yesno " "grid_force_nomin " "no" "_n"    
"yesno " "grid_force_nomax " "no" "_n(2)"    
"yesno " "xyline_extend_low " "yes" "_n"    
"yesno " "xyline_extend_high " "yes" "_n(2)"    
"yesno " "alt_xaxes " "no" "_n"    
"yesno " "alt_yaxes " "no" "_n"    
"yesno " "x2axis_ontop " "yes" "_n"    
"yesno " "y2axis_onright " "yes" "_n(2)"    
"yesno " "use_labels_on_ticks " "yes" "_n(2)"    
"yesno " "alternate_labels " "no" "_n"    
"yesno " "swap_bar_scaleaxis " "no" "_n"    
"yesno " "swap_bar_groupaxis " "no" "_n"    
"yesno " "swap_dot_scaleaxis " "no" "_n"    
"yesno " "swap_dot_groupaxis " "no" "_n"    
"yesno " "swap_box_scaleaxis " "no" "_n"    
"yesno " "swap_box_groupaxis " "no" "_n"    
"yesno " "extend_dots " "yes" "_n"    
"yesno " "bar_reverse_scale " "no" "_n"    
"yesno " "dot_reverse_scale " "no" "_n"    
"yesno " "box_reverse_scale " "no" "_n(2)"    
"yesno " "box_hollow " "no" "_n"    
"yesno " "box_custom_whiskers " "no" "_n(2)"    
"yesno " "pie_clockwise " "yes" "_n(2)"    
"yesno " "by_edgelabel " "yes" "_n"    
"yesno " "by_alternate_xaxes " "no" "_n"    
"yesno " "by_alternate_yaxes " "no" "_n"    
"yesno " "by_skip_xalternate " "no" "_n"    
"yesno " "by_skip_yalternate " "no" "_n"    
"yesno " "by_outer_xtitles " "yes" "_n"    
"yesno " "by_outer_ytitles " "yes" "_n"    
"yesno " "by_outer_xaxes " "yes" "_n"    
"yesno " "by_outer_yaxes " "yes" "_n"    
"yesno " "by_indiv_xaxes " "no" "_n"    
"yesno " "by_indiv_yaxes " "no" "_n"    
"yesno " "by_indiv_xtitles " "no" "_n"    
"yesno " "by_indiv_ytitles " "no" "_n"    
"yesno " "by_indiv_xlabels " "yes" "_n"    
"yesno " "by_indiv_ylabels " "yes" "_n"    
"yesno " "by_indiv_xticks " "yes" "_n"    
"yesno " "by_indiv_yticks " "yes" "_n"    
"yesno " "by_indiv_xrescale " "no" "_n"    
"yesno " "by_indiv_yrescale " "no" "_n"    
"yesno " "by_indiv_as_whole " "no" "_n"    
"yesno " "by_shrink_plotregion " "no" "_n"    
"yesno " "by_shrink_indiv " "no" "_n(2)"    
"yesno " "mat_label_box " "yes" "_n"    
"yesno " "mat_label_as_textbox " "yes" "_n(2)"    
"yesno " "legend_col_first " "no" "_n"    
"yesno " "legend_text_first " "no" "_n"    
"yesno " "legend_stacked " "no" "_n"    
"yesno " "legend_force_keysz " "no" "_n"    
"yesno " "legend_force_draw " "no" "_n"    
"yesno " "legend_force_nodraw " "no" "_n(2)"    
"yesno " "title_span " "yes" "_n"    
"yesno " "subtitle_span " "yes" "_n"    
"yesno " "caption_span " "yes" "_n"    
"yesno " "note_span " "yes" "_n"    
"yesno " "legend_span " "yes" "_n"    
"yesno " "zyx2legend_span " "no" "_n"    
"yesno " "clegend_title_span " "yes" "_n(2)"    
"yesno " "adj_xmargins " "no" "_n"    
"yesno " "adj_ymargins " "no" "_n(2)"    
"yesno " "plabelboxed " "no" "_n"    
"yesno " "pboxlabelboxed " "no" "_n(2)"    
"yesno " "contours_outline " "no" "_n"    
"yesno " "contours_reversekey " "no" "_n"    
"yesno " "contours_colorlines " "no" "_n(2)"    
"* yesno " "p#labelboxed           " "no" "_n" 
"* yesno " "p#boxlabelboxed        " "no" "_n(3)"    
"barstyle " "" "default" "_n"    
"barstyle " "default " "default" "_n"    
"barstyle " "dot " "dotdefault" "_n"    
"barstyle " "box " "boxdefault" "_n(2)"    
"barlabelstyle " "     " "none" "_n"    
"barlabelstyle " "bar " "bar" "_n(2)"    
"dottypestyle " "dot " "dot" "_n(2)"    
"medtypestyle " "boxplot " "line" "_n(2)"    
"pielabelstyle " "default " "none" "_n(2)"    
"arrowstyle " "default " "editor" "_n"    
"arrowstyle " "editor " "editor" "_n(2)"    
"starstyle " "" "default" "_n"    
"starstyle " "default " "default" "_n(2)"    
"above_below " "star " "below" "_n(2)"    
"zyx2rule " "contour " "intensity" "_n"    
"zyx2rule " "contour " "hue" "_n(2)"    
"zyx2style " "" "default" "_n"    
"zyx2style " "default " "default" "_n" 
`"* seriesstyle "' `"p1  "' `"line_circle"' `"_n"'
`"* seriesstyle "' `"p2  "' `"line_square"' `"_n"'
`"* seriesstyle "' `"p3  "' `"line_diamond"' `"_n"'
`"* seriesstyle "' `"p4  "' `"line_x"' `"_n"'
`"* seriesstyle "' `"p5  "' `"line_plus"' `"_n"'
`"* seriesstyle "' `"p6  "' `"line_triangle"' `"_n"'
`"* seriesstyle "' `"p7  "' `"line_smcircle"' `"_n(2)"'
`"* seriesstyle "' `"pa  "' `"line_xcircle"' `"_n"'
`"* seriesstyle "' `"pb  "' `"line_xsquare"' `"_n"'
`"* seriesstyle "' `"pc  "' `"line_xdiamond"' `"_n"'
`"* seriesstyle "' `"pd  "' `"line_xx"' `"_n"'
`"* seriesstyle "' `"pe  "' `"line_xplus"' `"_n"'
`"* seriesstyle "' `"pf  "' `"line_xtriangle"' `"_n"'
`"* seriesstyle "' `"pg  "' `"line_xsmcircle"' `"_n(2)"'
`"* seriesstyle "' `"ph  "' `"line_pcircle"' `"_n"'
`"* seriesstyle "' `"pi  "' `"line_psquare"' `"_n"'
`"* seriesstyle "' `"pj  "' `"line_pdiamond"' `"_n"'
`"* seriesstyle "' `"pk  "' `"line_px"' `"_n"'
`"* seriesstyle "' `"pl  "' `"line_pplus"' `"_n"'
`"* seriesstyle "' `"pm  "' `"line_ptriangle"' `"_n"'
`"* seriesstyle "' `"pn  "' `"line_psmcircle"' `"_n(2)"'
`"* seriesstyle "' `"po  "' `"line_dblcircle"' `"_n"'
`"* seriesstyle "' `"pp  "' `"line_dblsquare"' `"_n"'
`"* seriesstyle "' `"pq  "' `"line_dbldiamond"' `"_n"'
`"* seriesstyle "' `"pr  "' `"line_dblx"' `"_n"'
`"* seriesstyle "' `"ps  "' `"line_dblplus"' `"_n"'
`"* seriesstyle "' `"pt  "' `"line_dbltriangle"' `"_n"'
`"* seriesstyle "' `"pu  "' `"line_dblsmcircle"' `"_n(2)"'
`"* seriesstyle "' `"pv  "' `"wideline_circle"' `"_n"'
`"* seriesstyle "' `"pw  "' `"wideline_square"' `"_n"'
`"* seriesstyle "' `"px  "' `"wideline_diamond"' `"_n"'
`"* seriesstyle "' `"py  "' `"wideline_x"' `"_n"'
`"* seriesstyle "' `"pz  "' `"wideline_plus"' `"_n"'
`"* seriesstyle "' `"paa "' `"wideline_triangle"' `"_n"'
`"* seriesstyle "' `"pab "' `"wideline_smcircle"' `"_n(2)"'
`"* seriesstyle "' `"pac "' `"line_spcircle"' `"_n"'
`"* seriesstyle "' `"pad "' `"line_spsquare"' `"_n"'
`"* seriesstyle "' `"pae "' `"line_spdiamond"' `"_n"'
`"* seriesstyle "' `"paf "' `"line_spx"' `"_n"'
`"* seriesstyle "' `"pag "' `"line_spplus"' `"_n"'
`"* seriesstyle "' `"pah "' `"line_sptriangle"' `"_n"'
`"* seriesstyle "' `"pai "' `"line_spsmcircle"' `"_n"'
`"* seriesstyle "' `"paj "' `"line_sppoint"' `"_n(2)"'
`"* seriesstyle "' `"pak "' `"line"' `"_n"'
`"* seriesstyle "' `"pal "' `"dash"' `"_n"'
`"* seriesstyle "' `"pam "' `"dash_dot"' `"_n"'
`"* seriesstyle "' `"pan "' `"longdash"' `"_n"'
`"* seriesstyle "' `"pao "' `"dash_dotdot"' `"_n"'
`"* seriesstyle "' `"pap "' `"longshort"' `"_n"'
`"* seriesstyle "' `"paq "' `"shortdash"' `"_n(2)"'
`"* seriesstyle "' `"px "' `"wideline"' `"_n"'
`"* seriesstyle "' `"px  "' `"widedash"' `"_n"'
`"* seriesstyle "' `"px  "' `"widedash_dot"' `"_n"'
`"* seriesstyle "' `"px  "' `"widelongdash"' `"_n"'
`"* seriesstyle "' `"px  "' `"widedash_dotdot"' `"_n"'
`"* seriesstyle "' `"px  "' `"widelongshort"' `"_n"'
`"* seriesstyle "' `"px  "' `"wideshortdash"' `"_n(2)"'
`"* seriesstyle "' `"px  "' `"thinline"' `"_n"'
`"* seriesstyle "' `"px  "' `"thindash"' `"_n"'
`"* seriesstyle "' `"px  "' `"thindash_dot"' `"_n"'
`"* seriesstyle "' `"px  "' `"thinlongdash"' `"_n"'
`"* seriesstyle "' `"px  "' `"thindash_dotdot"' `"_n"'
`"* seriesstyle "' `"px  "' `"thinlongshort"' `"_n"'
`"* seriesstyle "' `"px  "' `"thinshortdash"' `"_n(2)"'			
`"sunflowerstyle "' `"sunflower "' `"sunflower"' `"_n"'
end

qui: g argname = subinstr(argnm, " ", "", .)

qui: g classname = subinstr(classnm, " ", "", .)

qui: replace classname = 	cond(classname == "above_below", "abovebelow", 	 ///   
							cond(classname == "numticks_g", "numticks",		 ///   
							cond(classname == "relative_posn", "relativepos", ///   
							cond(classname == "tb_orientstyle", "orientstyle", ///   
							cond(classname == "vertical_text", "verticaltext", ///   
							classname)))))

la var classnm "Scheme File Class Name"
la var argnm "Scheme File Argument Name"
la var value "Scheme File Parameter Value"
la var newline "Scheme File Lines to Insert Following This Line"
la var classname "Scheme File Class Name w/o Spaces"
la var argname "Argument Name w/o Spaces"

// Creates alternatve value variables for different forms of color blindness
foreach v in achromatopsia protanopia deuteranopia tritanopia {
	qui: g `v' = ""
}

mata: brewc.getNames(1, 1)

// Prepopulate the transformed values so only changes required are those from 
// User supplied arguments in brewtheme
forv i = 1/976 {

	// Get value
	loc val `"`: di value[`i']'"'
	
	if `i' == 382 {
	
		foreach v in achromatopsia protanopia deuteranopia tritanopia {
			qui: replace `v' = "" in 382
		}

	}

	// If it is one of the Stata named color styles
	else if `: list val in colornames' == 1 & `"`val'"' != "none" {

		// Set the values based on the named colors installed by brewcolordb
		qui: replace achromatopsia = `"`val'_achromatopsia"' in `i'
		
		qui: replace protanopia = `"`val'_protanopia"' in `i'
		
		qui: replace deuteranopia = `"`val'_deuteranopia"' in `i'
		
		qui: replace tritanopia = `"`val'_tritanopia"' in `i'
		
	} // End IF Block for Stata Named colors
	
	else if `"`val'"' == "none" {
	
		foreach v in achromatopsia protanopia deuteranopia tritanopia {
			qui: replace `v' = "none" in `i'
		}
	
	}
	
	// Otherwise
	else {
		mata: brewc.brewNameSearch(`"`: di value[`i']'"')	
		foreach v in achromatopsia protanopia deuteranopia tritanopia {
			qui: replace `v' = `"``v''"' if _n == `i'
		}
	}
}	
